name: Daily Athena Report

on:
  schedule:
    - cron: "0 0 * * *"   
  workflow_dispatch: {}   

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install boto3 pandas matplotlib pyarrow

      - name: Configure AWS creds
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws sts get-caller-identity

      - name: Run report script
        env:
          ATHENA_DB: weather
          ATHENA_OUTPUT: s3://iseunggi-weather-pipeline/athena-results/
        run: python scripts/athena_report.py

      - name: Commit report images
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/images/*.png
          git commit -m "chore(report): update daily charts" || echo "No changes to commit"
          git push
